### ISSUE TITLE
App keeps getting paused

### ISSUE THREAD

**Issue by EricMB73** [robertraaijmakers/com.trashchecker#141]
Hi,
The last couple of days the app is paused regularly.
Even restarting the app every day at noon is no help.
I am at the latest RC version, but the issue was already there on the latest stable version.
Any idea what could be the problem?

thanks!

**Comment by TheMatrix46** [comment]
Here the same problem after installation of 7.4.0-rc22 on a Homey Pro. Reinstall doesn’t work or help. It’s not possible to choose a address or services.

**Comment by robertraaijmakers** [comment]
Thanks, I’ve seen some memory warnings over the past couple of days. Which API are you using?

**Comment by EricMB73** [comment]
Hi,
I am using Mijn Afvalwijzer (NL)

**Comment by TheMatrix46** [comment]
> Thanks, I’ve seen some memory warnings over the past couple of days. Which API are you using?

I don't get a API, no response on PC + house number or hand choosing API.

**Comment by robertraaijmakers** [comment]
What postal code are you trying @TheMatrix46 ?

**Comment by robertraaijmakers** [comment]
Are you all on the latest (RC) version of Homey? (v7.4.0)

**Comment by EricMB73** [comment]
Yes, I am on 7.4.0-RC.22

**Comment by robertraaijmakers** [comment]
There has been a huge update in Homey in that version and that is probably causing this issue. I will try and have a look at it but is going to be hard since I don't own a Homey at this moment. Hopefully in September I have a new one again, but that will take a while ;) Will do my best

**Comment by PeterKawa** [comment]
Hi Robert,
This is partly what Adrian Rockall wrote. Maybe useful
![Screenshot_20220420-155642_Chrome](https://user-images.githubusercontent.com/74005072/164247153-76b8a2be-bfc3-449c-bdf6-3cbf54053d71.jpg)

**Comment by ENhomey** [comment]
> Yes, I am on 7.4.0-RC.22



> Same problem here. zip code 5237LE Den Bosch Afvalstoffendienstkalender (NL)
> 
> diagnostisch rapport fb61749e-249d-4b4d-849c-ad5c40e07670

Yes, I am on 7.4.0-RC.22

**Comment by robertraaijmakers** [comment]
@PeterKawa do you have a link to the source? It might be the case in this app as well. A lot of web API calls are done for all different providers. DenBosch & Afvalwijzer are using the same implementation under the hood, so there might be a correlation.

**Comment by GitMike1233** [comment]
I did not update to RC 7.4.0 because of some problems.
I only want to say thank you for supporting the app. Keep up the good work.
Thanks.

**Comment by robertraaijmakers** [comment]
All, I have done some changes, there were some bugs in de RD4 API that might cause some issues with the new version. Furthermore I added some extra error handling to see if that solves all the 'unhandled error' messages.

The test version is available here: https://homey.app/a/com.trashchecker/test/

@GitMike1233 thank you very much, much appreciated!

**Comment by TheMatrix46** [comment]
Oeps still problems, App paused again, collecting days are gone

**Comment by TheMatrix46** [comment]
38143915-5fb3-47d5-94aa-d6e756dbc4a2

**Comment by robertraaijmakers** [comment]
Thanks for all the info, I think I might have found the issue, but it will take some time to resolve since I have to rewrite all APIs. And when doing so, I also want to remove some deprecated functions that have been used in the past. But will need some time.

**Comment by EricMB73** [comment]
Hi, 
Take the time you need ofcourse !
Just happy  you keep supporting the app.

Thanks !

**Comment by robertraaijmakers** [comment]
I have rebuild the app, and can't test it myself, so I have absolutely no idea how stable it is now. But if someone is willing to test it that would be great. https://homey.app/a/com.trashchecker/test/

**Comment by PeterKawa** [comment]
Hi @robertraaijmakers 
I installed v7.4.0-rc22 yesterday and just now installed your app to test.
v3.1.6 and v3.1.7 test work fine so far.
I use the HVC API.
Let me know if I can do some tests.

**Comment by EricMB73** [comment]
Ofcourse we will test it !
Just installed 3.1.7 with AfvalWijzer.NL api

**Comment by EricMB73** [comment]
Sorry, it’s stuck at “Checking Adres”
Mijn AfvalWijzer (NL) with 1141SL

**Comment by PeterKawa** [comment]
@EricMB73 odd, that works here:
![Screenshot_20220422-172716_Homey](https://user-images.githubusercontent.com/74005072/164745950-87d65df1-69f2-4ca2-87dd-dc3bc3459d3c.jpg)
Can you try 1747tc / 1 HVC api?

**Comment by TheMatrix46** [comment]
No collection days or response, the app is pauzed. I have tried the suggested PC and Api

**Comment by TheMatrix46** [comment]
![image](https://user-images.githubusercontent.com/89856931/164757206-46ae103f-d89a-457c-af3a-efcdd18dc7b5.jpeg)

**Comment by EricMB73** [comment]
Doesn’t work either….

**Comment by robertraaijmakers** [comment]
Thanks for all the feedback. The memory thing is very strange... seems like something gets stuck in a loop and data isn't cleaned. But that will be hard to prove / find.

I just published a new test version based on the error logs that I got. So hopefully that does something.

**Comment by PeterKawa** [comment]
Thanks Robert. On the previous version v1.3.7 I could change the postal code and API a few times, later on I encountered the same situaton as EricMB. The message "checking for address" never disappears. Then I installed v1.3.8, but this issue is still present.
At the moment of "checking address", I created a diag. report, maybe it shows someting:
9288f2dc-95ac-4430-bf43-59cc339c3e41
My app doesn't quit or pause by the way, and it's configured okay for me, I managed to enter my postal code and API. The collect dates are correct too.

**Comment by robertraaijmakers** [comment]
Thanks @PeterKawa! I saw the debug log and it was actually very usefull.
The app is programmed to only retrieve the dates once a week. Somehow this functionality seems to be broken and now it pings the API every 1000ms. Which explains the memory explosion and also maybe some crashes.
I have now (hopefully) set it back to every 6 hours for now, since fixing this timing issue is quite hard without a Homey to debug since it uses some internal Homey functions to retrieve the local time and they seem to have changed/broken somehow.

For now I hope that with version 3.1.10 it starts to work for most people again. However, I had to make some other changes as well. So please retest and sending the logs (from users of who the app isn't crashing) is very usefull. I sometimes get manual logs from users where the app has crashed, and then the log is empty, so utterly useless :)

**Comment by EricMB73** [comment]
Sorry, still the same here

**Comment by PeterKawa** [comment]
You're welcome Robert. And thank you for your effort!
v3.1.10 didn't solve it for me, still the "checking address" thing.
I installed v3.1.5, and address was checked within a sec. and collect data was loaded.
Then I made a diag, so maybe you can compare stuff.

Now v3.1.10 is installed again, but I'm afraid the API can't be reached, b/c when I press "save" (while nothing was changed), the "checking" message doesn't disappear.

The memory useage seems less 30-40MB now

**Comment by TheMatrix46** [comment]
3.1.10 gifs collection days. Memory use is very high
![image](https://user-images.githubusercontent.com/89856931/164800994-d9cb1b50-d0f1-4a6f-ad7d-2bf824f8496e.jpeg)

**Comment by PeterKawa** [comment]
Apps get killed when the memory useage reaches around 80MB. That can explain why the app gets paused.

**Comment by EricMB73** [comment]
Hmm, I was able to enter my address and it was found.  
Until now no pause on the app…
Memory usage is a bit high

I really appreciate all the work you are doing to solve this!!

**Comment by robertraaijmakers** [comment]
Thanks. I have just released 3.1.12 to the test channel.

3.1.11 : This seems to be a working version, it is based on 3.1.5 with some minor changes (so doesn't contain the good error handling and also some of the API's didn't work due to changes that have been made, but I think this can be a stable version)

3.1.12 : This is a version based on the updated node.js core that is used in Homey 7.4.0-RC22. I think I found the issue with the settings page not being able to be safed. And also resolved the whole timing thing.

If the feedback from 3.1.12 is good (and maybe some people can submit some user logs :)) then this version can be released to production later on. If the feedback isn't good I'm going back to 3.1.11 for now until I have a Homey myself again, because then I really need to be able to live debug the whole thing.

**Comment by TheMatrix46** [comment]
fce2f564-4e00-4432-af7a-e265304f14d8

**Comment by TheMatrix46** [comment]
![image](https://user-images.githubusercontent.com/89856931/164887721-c4c9c8c7-ffa7-4112-8d0b-d21f845da15f.jpeg)

**Comment by robertraaijmakers** [comment]
Thanks, I have to contact Athom I guess, since the function that I used to retrieve the local date isn't working anymore in Homey 7.4.0-RC22.

getLocalDate()
{
  var date = new Date(new Date().toLocaleString('nl-NL', { timeZone: this.homey.clock.getTimezone() }));
  console.log(`Local date: ${date}`);
  return date;
}

This function returns: Local date: Invalid Date

And that means that even if the app doesn't crash anymore, it still won't be able to set the labels correctly.

**Comment by TheMatrix46** [comment]
Hi Robert, at the moment I am with my iPhone in a other time zone. Homey of course not.

Met vriendelijke groet,

Peter Veenendaal

✉️ ***@***.***
☎️ +31 6 83 207 092
________________________________
Van: Robert ***@***.***>
Verzonden: Saturday, April 23, 2022 10:34:42 AM
Aan: robertraaijmakers/com.trashchecker ***@***.***>
CC: TheMatrix46 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [robertraaijmakers/com.trashchecker] App keeps getting paused (Issue #141)


Thanks, I have to contact Athom I guess, since the function that I used to retrieve the local date isn't working anymore in Homey 7.4.0-RC22.

getLocalDate()
{
var date = new Date(new Date().toLocaleString('nl-NL', { timeZone: this.homey.clock.getTimezone() }));
console.log(Local date: ${date});
return date;
}

This function returns: Local date: Invalid Date

And that means that even if the app doesn't crash anymore, it still won't be able to set the labels correctly.

**Comment by TheMatrix46** [comment]
At the moment my iPone is in a other time zone then Homey is. 1 hour time difference. Could that be a problem?

**Comment by TheMatrix46** [comment]
755989cd-3012-4fa0-bbf3-8911c3fddb78

**Comment by TheMatrix46** [comment]
![image](https://user-images.githubusercontent.com/89856931/164891260-f4f23732-a62d-4858-be50-5d33e5816874.jpeg)

**Comment by EricMB73** [comment]
Seems to be working here….no more paused apps

**Comment by PeterKawa** [comment]
Thanks again Robert! 
v3.1.12 address can be saved, and changed no issues.
a70aa5c0-42a8-4be7-a6c2-def7fccb757c
Memory around 15-20MB
![Screenshot_20220423-152555_Homey](https://user-images.githubusercontent.com/74005072/164896635-f080be8d-a8d0-44bc-91dc-3c6497f92f47.jpg)

**Comment by TheMatrix46** [comment]
![image](https://user-images.githubusercontent.com/89856931/164915171-8a04b264-fae9-44ff-9e12-d494ec0579b4.jpeg) memory usage is stable v3.1.12

**Comment by PeterKawa** [comment]
@TheMatrix46 It's still pretty high a your Homey.
I'm on a 512MB 'half' Pro btw.
![Screenshot_20220423-211234_Chrome](https://user-images.githubusercontent.com/74005072/164944965-96789b06-488c-4ab7-b555-90add6e818a0.jpg)

**Comment by EricMB73** [comment]
Memory-usage is not that high anymore after 15.00, but cpu load is rising every hour…

**Comment by TheMatrix46** [comment]
![image](https://user-images.githubusercontent.com/89856931/164948233-17246400-1d30-41b5-8e95-bbd7ae00c7a6.jpeg) update usage v3.1.12

**Comment by robertraaijmakers** [comment]
Thanks all for the extensive testing and feedback! This really helps :)

Good to see that the APIs are at least working, I will contact Athom this Monday if I can find my Slack credentials somewhere to see how the local time thing can be fixed and then I hope that the actual reminders will start to work again as well.

For now it seems that the memory leaks are fixed, so that is good news. On the processor part, are more people seeing that it takes up more and more of the processor? And is the processor reset every x-hours or does it keep increasing day-after-day?

**Comment by PeterKawa** [comment]
![Screenshot_20220424-141254_Chrome](https://user-images.githubusercontent.com/74005072/164976048-a3ee47c6-2ae8-4b72-b1cd-14e6ed229dcb.jpg)

No clue what the cpu % numbers stand for

**Comment by TheMatrix46** [comment]
Robert, thanks for the debugging and coding. It was nice to give a little help.

**Comment by TheMatrix46** [comment]
25-4-2022
![image](https://user-images.githubusercontent.com/89856931/165070094-ecf5ee26-517c-4b56-88b7-cc859dbb177f.jpeg)

**Comment by robertraaijmakers** [comment]
Thanks again all for testing! If somebody can let me know if they actually receive a notification from the app when their trash is collected, that would be great (on test version 3.1.13). Then I will push the app to the stable channel.

**Comment by PeterKawa** [comment]
Seems to run fine, Robert! 
V3.1.13
https://homey.app/f/K0GHB1

![Screenshot_20220426-134549_One UI Home](https://user-images.githubusercontent.com/74005072/165293120-14d7c2c7-3310-46c3-ad2e-8bd1956f3d79.jpg)

**Comment by EricMB73** [comment]
Hi Robert,
Everything seems to be working again…

Eric

**Comment by robertraaijmakers** [comment]
The new version (3.1.13) has been released to stable and should resolve the issues as tested. I will close this issue. Thanks again for all the support!
